### Introducción

Este notebook tendrá pruebas de entrenamiento de los modelos de regresión logística, árbol de decisión y random forest

### Importación de librerías

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns

from sklearn.preprocessing import StandardScaler

from matplotlib.colors import ListedColormap

from sklearn.linear_model import LogisticRegression

from sklearn.ensemble import RandomForestClassifier

from sklearn.tree import (
    DecisionTreeClassifier,
    plot_tree
)

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    roc_curve,
    roc_auc_score
)

### Definición de constantes

In [2]:
PATH_DIRECTORIO_DATOS_PREPROCESSED = "../../data/processed"
PATH_DATASET_PREPROCCESSED = f"{PATH_DIRECTORIO_DATOS_PREPROCESSED}/dataset_practica_final_preprocessed.csv"

### Regresión Logística

#### Lectura de datos

In [3]:
df_hotel = pd.read_csv(PATH_DATASET_PREPROCCESSED)

#### Preprocesamiento de datos

Mostramos las primeras y las últimas filas del dataframe, la dimension y los tipos de datos.

In [4]:
# Primeras filas del dataframe

df_hotel.head()

,hotel,is_canceled,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
0,Resort Hotel,0,342,July,27,1,0,0,2,0,...,0,C,C,3,No Deposit,0,Transient,0.0,0,0
1,Resort Hotel,0,737,July,27,1,0,0,2,0,...,0,C,C,4,No Deposit,0,Transient,0.0,0,0
2,Resort Hotel,0,7,July,27,1,0,1,1,0,...,0,A,C,0,No Deposit,0,Transient,75.0,0,0
3,Resort Hotel,0,13,July,27,1,0,1,1,0,...,0,A,A,0,No Deposit,0,Transient,75.0,0,0
4,Resort Hotel,0,14,July,27,1,0,2,2,0,...,0,A,A,0,No Deposit,0,Transient,98.0,0,1

In [ ]:
# Últimas filas del dataframe

df_hotel.tail()

,hotel,is_canceled,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
118892,City Hotel,0,23,August,35,30,2,5,2,0,...,0,A,A,0,No Deposit,0,Transient,96.14,0,0
118893,City Hotel,0,102,August,35,31,2,5,3,0,...,0,E,E,0,No Deposit,0,Transient,225.43,0,2
118894,City Hotel,0,34,August,35,31,2,5,2,0,...,0,D,D,0,No Deposit,0,Transient,157.71,0,4
118895,City Hotel,0,109,August,35,31,2,5,2,0,...,0,A,A,0,No Deposit,0,Transient,104.40,0,0
118896,City Hotel,0,205,August,35,29,2,7,2,0,...,0,A,A,0,No Deposit,0,Transient,151.20,0,2

In [6]:
# Dimension del dataframe

df_hotel.shape

(118897, 27)

In [7]:
# Información del tipo de datos del dataframe

df_hotel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118897 entries, 0 to 118896
Data columns (total 27 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           118897 non-null  object
 1   is_canceled                     118897 non-null  int64
 2   lead_time                       118897 non-null  int64
 3   arrival_date_month              118897 non-null  object
 4   arrival_date_week_number        118897 non-null  int64
 5   arrival_date_day_of_month       118897 non-null  int64
 6   stays_in_weekend_nights         118897 non-null  int64
 7   stays_in_week_nights            118897 non-null  int64
 8   adults                          118897 non-null  int64
 9   children                        118897 non-null  int64
 10  babies                          118897 non-null  int64
 11  meal                            118897 non-null  object
 12  country                         118897 non-null  object
 13  market_segment                  118897 non-null  object
 14  distribution_channel            118897 non-null  object
 15  is_repeated_guest               118897 non-null  int64
 16  previous_cancellations          118897 non-null  int64
 17  previous_bookings_not_canceled  118897 non-null  int64
 18  reserved_room_type              118897 non-null  object
 19  assigned_room_type              118897 non-null  object
 20  booking_changes                 118897 non-null  int64
 21  deposit_type                    118897 non-null  object
 22  days_in_waiting_list            118897 non-null  int64
 23  customer_type                   118897 non-null  object
 24  adr                             118897 non-null  float64
 25  required_car_parking_spaces     118897 non-null  int64
 26  total_of_special_requests       118897 non-null  int64
dtypes: float64(1), int64(16), object(10)
memory usage: 24.5+ MB